version: '3'
services:
  gpx2fit:
    container_name: gpx2fit
    image: gpx2fit:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - BASE_URL=http://localhost:5500
    restart: unless-stopped